CREATE TABLE IF NOT EXISTS "orderItems" (
  id SERIAL NOT NULL PRIMARY KEY,
  "orderId" INTEGER NOT NULL,
  "productId" INTEGER NOT NULL,
  quantity INTEGER NOT NULL,
  price DOUBLE PRECISION NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_order FOREIGN KEY("orderId") REFERENCES orders(id),
  CONSTRAINT fk_product FOREIGN KEY("productId") REFERENCES products(id)
);